# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - master
      - '[0-9].*'
  pull_request:
    branches:
      - master
      - '[0-9].*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11, 17 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Print tool versions
        run: |
          java -version
          ./gradlew --version

      - run: ./gradlew check
      - run: ./gradlew jacocoTestReport aggregateJacocoReport
      - name: Upload coverage report
        uses: codecov/codecov-action@v2.1.0
        with:
          files: jacoco*.xml,*Jacoco*.xml
